# Generated by Django 3.2.6 on 2021-11-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sr_no', models.IntegerField()),
                ('name', models.CharField(max_length=500)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='DOB',
            field=models.CharField(max_length=500),
        ),
    ]
